spring.application.name=TempShop

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.adihwadrjrqtrbctnchz
spring.datasource.password=999107201012606

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true